"""Stable, script-friendly API for analyzing saved JavaScript assets."""

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Union

from .extractors import ExtractorOrchestrator, NativeRegexExtractor
from .layout import OutputLayout
from .models import Finding
from .reconstructor import SourceMapReconstructor
from .reporting import ReportGenerator, write_summary


@dataclass(frozen=True)
class ScanOptions:
    """Options for an offline asset analysis run."""

    minimum_severity: str = "INFO"
    extract_sources: bool = False
    extract_strings: bool = False
    report_format: str = "json"


@dataclass
class ScanResult:
    """Artifacts and findings generated by :func:`analyze_directory`."""

    input_directory: Path
    output_directory: Path
    findings: List[Finding]
    report_paths: Dict[str, Path]
    sources_directory: Optional[Path] = None
    strings: Optional[Dict] = None

    @property
    def finding_count(self) -> int:
        return len(self.findings)


def analyze_directory(
    directory: Union[str, Path],
    output: Union[str, Path],
    options: Optional[ScanOptions] = None,
) -> ScanResult:
    """Analyze local JavaScript assets and write reports to *output*.

    This function makes no network requests. It is intended for assets you own
    or are authorized to assess.
    """
    input_directory = Path(directory).expanduser().resolve()
    if not input_directory.is_dir():
        raise ValueError(f"Input directory does not exist: {input_directory}")

    options = options or ScanOptions()
    if options.minimum_severity not in {"CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"}:
        raise ValueError("minimum_severity must be CRITICAL, HIGH, MEDIUM, LOW, or INFO")
    if options.report_format not in {"json", "csv", "md", "txt", "html"}:
        raise ValueError("report_format must be json, csv, md, txt, or html")

    layout = OutputLayout(Path(output).expanduser())
    layout.create_all()
    extractor = NativeRegexExtractor(options.minimum_severity)
    findings = ExtractorOrchestrator().register(extractor).analyze(input_directory)

    sources_directory = None
    strings = None
    reconstructor = SourceMapReconstructor(layout)
    if options.extract_sources:
        sources_directory = reconstructor.extract(input_directory)
    if options.extract_strings:
        strings = reconstructor.extract_strings(input_directory)

    reporter = ReportGenerator(findings)
    report_paths = {"json": layout.report_path("json"), "html": layout.report_path("html")}
    reporter.save(report_paths["json"], "json")
    reporter.save(report_paths["html"], "html")
    if options.report_format not in report_paths:
        report_paths[options.report_format] = layout.report_path(options.report_format)
        reporter.save(report_paths[options.report_format], options.report_format)
    write_summary(layout, str(input_directory), findings, {"ok": 0, "skipped": 0, "failed": 0}, None)

    return ScanResult(input_directory, layout.root, findings, report_paths, sources_directory, strings)
