"""Comprehensive, script-friendly API for downloading, analyzing, and reconstructing JavaScript assets."""

import json
import tempfile
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from .downloader import ChunkDownloader
from .extractors import (
    ExtractorOrchestrator,
    NativeRegexExtractor,
    RipgrepExtractor,
    TruffleHogExtractor,
)
from .layout import OutputLayout
from .models import Finding
from .network import build_session
from .beautifier import (
    beautify_code,
    beautify_css,
    beautify_file,
    beautify_html,
    beautify_javascript,
    clean_minified_syntax,
)
from .debundler import (
    DebundleResult,
    debundle_directory,
    debundle_file,
    extract_bundle_architecture,
    extract_webpack_modules,
)
from .reconstructor import (
    ReconstructionResult,
    SourceMapReconstructor,
    unpack_sourcemap_to_dict,
)
from .reporting import ReportGenerator, write_summary


@dataclass(frozen=True)
class ScanOptions:
    """Options for an offline asset analysis run."""

    minimum_severity: str = "INFO"
    extract_sources: bool = False
    extract_strings: bool = False
    report_format: str = "json"
    redact_values: bool = False
    use_trufflehog: bool = False
    use_ripgrep: bool = False
    beautify: bool = True
    debundle: bool = True


@dataclass
class ScanResult:
    """Artifacts and findings generated by :func:`analyze` or :func:`analyze_directory`."""

    input_directory: Path
    output_directory: Path
    findings: List[Finding]
    report_paths: Dict[str, Path]
    sources_directory: Optional[Path] = None
    strings: Optional[Dict] = None

    @property
    def finding_count(self) -> int:
        return len(self.findings)

    @property
    def critical_findings(self) -> List[Finding]:
        return [f for f in self.findings if f.severity == "CRITICAL"]

    @property
    def high_findings(self) -> List[Finding]:
        return [f for f in self.findings if f.severity == "HIGH"]

    def has_severity_at_least(self, threshold: str) -> bool:
        """Return whether any finding meets or exceeds *threshold*."""
        order = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
        if threshold not in order:
            raise ValueError("threshold must be CRITICAL, HIGH, MEDIUM, LOW, or INFO")
        return any(order.index(item.severity) <= order.index(threshold) for item in self.findings)

    def findings_by_severity(self) -> Dict[str, List[Finding]]:
        result: Dict[str, List[Finding]] = defaultdict(list)
        for f in self.findings:
            result[f.severity].append(f)
        return dict(result)

    def findings_by_category(self) -> Dict[str, List[Finding]]:
        result: Dict[str, List[Finding]] = defaultdict(list)
        for f in self.findings:
            result[f.category].append(f)
        return dict(result)

    def to_dict(self) -> dict:
        return {
            "input_directory": str(self.input_directory),
            "output_directory": str(self.output_directory),
            "total_findings": len(self.findings),
            "findings": [f.to_dict() for f in self.findings],
            "report_paths": {k: str(v) for k, v in self.report_paths.items()},
            "sources_directory": str(self.sources_directory) if self.sources_directory else None,
        }


@dataclass
class DownloadResult:
    """Artifacts produced by :func:`download`."""

    output_directory: Path
    chunks_directory: Path
    maps_directory: Path
    stats: Dict[str, int]
    sources_directory: Optional[Path] = None
    downloaded_files: List[str] = field(default_factory=list)


def scan_code(
    code: str,
    filename: str = "snippet.js",
    minimum_severity: str = "INFO",
) -> List[Finding]:
    """Analyze an in-memory string of JavaScript/TypeScript code.

    Returns a list of :class:`Finding` objects.
    """
    with tempfile.NamedTemporaryFile("w", suffix=".js", encoding="utf-8", delete=False) as tf:
        tf.write(code)
        temp_path = Path(tf.name)

    try:
        extractor = NativeRegexExtractor(min_severity=minimum_severity)
        findings = extractor.analyze_file(temp_path)
        # Fix file name label
        for f in findings:
            f.file = filename
        return findings
    finally:
        try:
            temp_path.unlink()
        except OSError:
            pass


def scan_file(
    filepath: Union[str, Path],
    minimum_severity: str = "INFO",
) -> List[Finding]:
    """Analyze a single JavaScript or TypeScript file for secrets and endpoints."""
    p = Path(filepath).expanduser().resolve()
    if not p.is_file():
        raise FileNotFoundError(f"File does not exist: {filepath}")
    extractor = NativeRegexExtractor(min_severity=minimum_severity)
    return extractor.analyze_file(p)


def reconstruct(
    source: Union[str, Path, List[Union[str, Path]], dict],
    output_dir: Optional[Union[str, Path]] = None,
    session: Optional[Any] = None,
    base_url: Optional[str] = None,
    beautify: bool = True,
    debundle: bool = True,
) -> ReconstructionResult:
    """Reconstruct original source code from a .map file, a .js file, a directory, or raw source files.

    *source* can be a path to a .map file, a .js file (with inline or referenced map),
    a directory of bundles or crawled source files (.tsx/.ts/etc.), a raw sourcemap JSON string,
    or a parsed dictionary.

    When no sourcemaps are found, automatically debundles and beautifies chunks into readable modules.
    Returns a :class:`ReconstructionResult`.
    """
    out_path = Path(output_dir).expanduser().resolve() if output_dir else Path("extracted_sources").resolve()
    recon = SourceMapReconstructor(
        output_dir=out_path,
        session=session,
        base_url=base_url,
        beautify=beautify,
        debundle=debundle,
    )
    return recon.reconstruct(source)


def debundle(
    target: Union[str, Path],
    output_dir: Union[str, Path],
    beautify: bool = True,
) -> DebundleResult:
    """Debundle JavaScript bundle(s) into individual readable module files.

    Extracts Webpack modules and generates an ARCHITECTURE.md application blueprint.
    """
    p = Path(target).expanduser().resolve()
    if p.is_file():
        return debundle_file(p, output_dir, beautify=beautify)
    elif p.is_dir():
        return debundle_directory(p, output_dir, beautify=beautify)
    else:
        raise FileNotFoundError(f"Target not found: {target}")


def get_architecture(target: Union[str, Path]) -> Dict[str, Any]:
    """Extract frontend routes, API endpoints, components, and storage keys from code or bundle."""
    p = Path(target).expanduser().resolve()
    if p.is_file():
        content = p.read_text(encoding="utf-8", errors="ignore")
        return extract_bundle_architecture(content, filename=p.name)
    elif p.is_dir():
        with tempfile.TemporaryDirectory() as td:
            res = debundle_directory(p, td)
            return {
                "routes": res.routes,
                "endpoints": res.endpoints,
                "components": res.components,
            }
    else:
        return extract_bundle_architecture(str(target), filename="snippet.js")


def unpack_sourcemap(
    sourcemap: Union[str, Path, dict],
    output_dir: Optional[Union[str, Path]] = None,
    source_root: Optional[str] = None,
) -> Dict[str, str]:
    """Unpack a sourcemap into a dictionary mapping relative source paths to source code.

    If *output_dir* is provided, source files are also written to disk safely.
    """
    sources_dict = unpack_sourcemap_to_dict(sourcemap, source_root=source_root)
    if output_dir:
        recon = SourceMapReconstructor(output_dir=output_dir)
        for rel_path, content in sources_dict.items():
            recon._safe_write_file(rel_path, content)
    return sources_dict


def extract_strings(
    target: Union[str, Path],
    output_file: Optional[Union[str, Path]] = None,
) -> Dict[str, List[dict]]:
    """Extract URLs, endpoints, paths, and emails from JavaScript files."""
    recon = SourceMapReconstructor()
    data = recon.extract_strings(target)
    if output_file:
        out_p = Path(output_file).expanduser().resolve()
        out_p.parent.mkdir(parents=True, exist_ok=True)
        out_p.write_text(json.dumps(data, indent=2), encoding="utf-8")
    return data


def download(
    url: str,
    output: Optional[Union[str, Path]] = None,
    threads: int = 5,
    delay: float = 0.0,
    headers: Optional[Union[dict, list]] = None,
    cookies: Optional[str] = None,
    proxy: Optional[str] = None,
    verify: bool = True,
    extract_sources: bool = False,
    crawl_esm: bool = True,
    deep: bool = False,
    beautify: bool = True,
    debundle: bool = True,
) -> DownloadResult:
    """Download JavaScript chunks and source maps from *url*.

    Optionally crawls ES module dependency graphs (e.g. main.tsx -> App.tsx),
    deeply inspects bundles for lazy-loaded chunks and dynamic imports,
    beautifies downloaded assets for readability, and reconstructs sources if *extract_sources* is True.
    """
    root = Path(output).expanduser().resolve() if output else Path(f"jsmap_dl_{Path(url).name or 'target'}").resolve()
    layout = OutputLayout(root)
    layout.create_all()

    session = build_session(
        url=url,
        proxy=proxy,
        no_verify=not verify,
        cookie=cookies,
        header=headers,
    )
    downloader = ChunkDownloader(
        session,
        url,
        layout=layout,
        threads=threads,
        delay=delay,
        crawl_esm=crawl_esm,
        deep=deep,
        beautify=beautify,
    )
    chunk_map, special_names, extra_scripts = downloader.auto_detect_chunks()
    chunks_dir = downloader.download_all(chunk_map, special_names, extra_scripts)

    src_dir = None
    if extract_sources:
        recon = SourceMapReconstructor(
            layout=layout,
            session=session,
            base_url=url,
            beautify=beautify,
            debundle=debundle,
        )
        src_dir = recon.extract(chunks_dir)

    downloaded = [f.name for f in chunks_dir.rglob("*") if f.is_file()]
    return DownloadResult(
        output_directory=layout.root,
        chunks_directory=layout.chunks_dir,
        maps_directory=layout.maps_dir,
        stats=downloader.stats,
        sources_directory=src_dir,
        downloaded_files=downloaded,
    )


def analyze(
    target: Union[str, Path],
    output: Optional[Union[str, Path]] = None,
    options: Optional[ScanOptions] = None,
) -> ScanResult:
    """Analyze local JavaScript assets (directory or single file) and write reports.

    This function makes no network requests.
    """
    target_path = Path(target).expanduser().resolve()
    if not target_path.exists():
        raise ValueError(f"Target does not exist: {target_path}")

    options = options or ScanOptions()
    if options.minimum_severity not in {"CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"}:
        raise ValueError("minimum_severity must be CRITICAL, HIGH, MEDIUM, LOW, or INFO")
    if options.report_format not in {"json", "csv", "md", "txt", "html", "sarif"}:
        raise ValueError("report_format must be json, csv, md, txt, html, or sarif")

    out_root = Path(output).expanduser().resolve() if output else Path(f"jsmap_analysis_{target_path.name}").resolve()
    layout = OutputLayout(out_root)
    layout.create_all()

    orchestrator = ExtractorOrchestrator()
    orchestrator.register(NativeRegexExtractor(options.minimum_severity))

    if options.use_trufflehog:
        th = TruffleHogExtractor()
        if th.is_available():
            orchestrator.register(th)

    if options.use_ripgrep:
        rg = RipgrepExtractor()
        if rg.is_available():
            orchestrator.register(rg)

    if target_path.is_dir():
        findings = orchestrator.analyze(target_path)
    else:
        findings = NativeRegexExtractor(options.minimum_severity).analyze_file(target_path)

    sources_directory = None
    strings = None
    reconstructor = SourceMapReconstructor(
        layout,
        beautify=options.beautify,
        debundle=options.debundle,
    )

    if options.extract_sources:
        sources_directory = reconstructor.extract(target_path)
        if sources_directory:
            additional = orchestrator.analyze(sources_directory)
            findings = list({f.value[:50] + f.file: f for f in findings + additional}.values())

    if options.extract_strings:
        strings = reconstructor.extract_strings(target_path)

    reporter = ReportGenerator(findings, redact_values=options.redact_values)
    report_paths = {"json": layout.report_path("json"), "html": layout.report_path("html")}
    reporter.save(report_paths["json"], "json")
    reporter.save(report_paths["html"], "html")
    if options.report_format not in report_paths:
        report_paths[options.report_format] = layout.report_path(options.report_format)
        reporter.save(report_paths[options.report_format], options.report_format)

    write_summary(layout, str(target_path), findings, {"ok": 0, "skipped": 0, "failed": 0}, None)
    return ScanResult(target_path, layout.root, findings, report_paths, sources_directory, strings)


def analyze_directory(
    directory: Union[str, Path],
    output: Union[str, Path],
    options: Optional[ScanOptions] = None,
) -> ScanResult:
    """Analyze local JavaScript assets in a directory and write reports to *output*.

    Maintained for full backward compatibility.
    """
    return analyze(target=directory, output=output, options=options)

